# ------------------------------------------------
# Camerons Ansible DAY 3 PlayBook 5
#
# Purpose:  Use facts to output windows or Linux
# ------------------------------------------------
---
- hosts: all
  gather_facts: yes

  tasks:
  # "Linux" on a Linux system and "Win32NT“ on Windows
  - name: Distribution
    debug: msg="{{ ansible_distribution }}"
  
  - name: This is linux
    debug: msg="Linux Server"
    when: ansible_system == "Linux"

  - name: This is windows
    debug: msg="Windows Server"
    when: ansible_system == "Win32NT" 
