---
# ------------------------------------------------
# Camerons Day 3 Playbook 3
# ------------------------------------------------
- name: "Show value of whoami using register"
  hosts: all
  tasks:
    - name: "Capture output of whoami command"
      win_shell: whoami
      register: login

    - debug: var=login.start
    - debug: var=login.cmd
